name: Deploy to Gist

on:
  push:
  schedule:
    - cron: "0 */8 * * *"

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: wget https://raw.githubusercontent.com/nonPointer/ClashHelper/master/helper.py -O helper.py 
      - run: python3 helper.py template.yaml Clash.yml | tee run.log
      - name: Deploy
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.TOKEN }}
          gist_id: 
          file_path: xingyuexicn/897e8ad1c4a4191893043cfcbd44417d
          file_type: binary
